# Generated by Django 5.0.3 on 2025-03-10 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_alter_tag_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-pub_time', 'price']},
        ),
        migrations.AlterModelTable(
            name='book',
            table='book_table',
        ),
    ]
